### PR TITLE
First pass adding LetsEncrypt support

### PR DESCRIPTION
**Pull request by hardillb**
Will need a to be paired with PR to flowforge-driver-docker (to add the extra env var) and for the docs in flowforge

To enable, update all the `example.com` entries and uncomment the all the commented out sections

### CODE REVIEW

**Comment by robmarcer** [comment]
@hardillb this version runs both with the comments in and out but I can't access https. I checked the logs for the acme-companion container and got...

```
Error: you need to share your Docker host socket with a volume at /var/run/docker.sock
Typically you should run your container with: '-v /var/run/docker.sock:/var/run/docker.sock:ro'
```

**Comment by hardillb** [comment]
I know what the problem is, I assumed that since the acme-companion came from the same team as the nginx-proxy they would be configured the same. They are subtly different, update inbound

**Comment by robmarcer** [comment]
This now works for me on my test build - https://d.pr/i/7knuiu

**Review by robmarcer — APPROVED** [review]
Seems to work now for me both with the commented sections in and out. I got a valid SSL cert on my test system.

**Pull request merged**
